---
title: "toolik_chlorophyll_summary"
format: html
editor: visual
execute: 
  echo: true
  warning: false
  #cache: TRUE -> code chunk won't be evaluated unless change has been made
---

```{r}
library(tidyverse)
library(janitor)
library(here)
library(skimr)
```

## Read in data

```{r}
toolik_chlorophyll <- read_csv(here::here("data", "data-raw", "toolik_chlorophyll.csv"),
                               na = c(".")) %>% #missing values were stored as "." this'll read the "." as "na"
  clean_names()
#check where you're starting by typing "read()" into console. First read data in THEN clean names

skim(toolik_chlorophyll)
 

```

```{r}
chlorophyll_pprod_graph <- ggplot(data = toolik_chlorophyll, 
                                  aes(x = active_chl_a_ug_l,
                                      y = pprod_mg_available_c_m3_d
                                      )) + geom_point()

chlorophyll_pprod_graph
  
```

```{r}
ggsave(plot = chlorophyll_pprod_graph, 
       here("figs", "my_graph.jpg"), 
            width = 8, height = 8, dpi = 200) #if data/coding is updated, saved graph will be updated too
```
